### PR TITLE
Fix "sed: can't read /etc/pve/qemu-server/....conf: No such file or d…

### PR DESCRIPTION
**Pull request by w3K-dot-co**
Fix "sed: can't read /etc/pve/qemu-server/....conf: No such file or directory" error

### CODE REVIEW

**Comment by emory** [comment]
do people realize that they're getting repositories set to .br local mirrors? i've been building macOS vms this week in proxmox and i didn't use this method but i looked at the scripting and didn't see much attempt to make it reversible or clear what is going on and allow the user to revert back easily.

i need to probably benchroom another proxmox server and see if i can help tidy this up a bit too, glad to see people submitting PRs!

**Comment by kubo6472** [comment]
I have no way of reaching you apart from apparently commenting on a PR. I tried this FOUR TIMES, each with different version of Proxmox VE, and got stuck at "loading initial ramdisk" each time. There must be something I'm overlooking. It's a clean installation and I'm running the one command only. The system reboots, and it's gone. Please tell me if you have ever encountered this, or there is some issue with my hardware. Thanks @luchina-gabriel

**Comment by tristan-k** [comment]
This is still an issue.

**Comment by i-oliva** [comment]
I'm getting this issue too...

**Pull request closed without merging**
