### PR TITLE
Fix post setup for the custom VM ID

### PR DESCRIPTION
**Pull request by ivan-leschinsky**
To fix this behaviour
screen 2022-06-26 at 12 39 04

### CODE REVIEW

**Comment by luchina-gabriel** [comment]
Hey, @ivan-leschinsky,

Excelent correction, thanks for much! :)

Regards,
Gabriel

**Comment by lepatrick** [comment]
Problem still exists:
Creating virtual machine with macOS - Ventura ...
sed: can't read /etc/pve/qemu-server/102.conf: No such file or directory
Virtual machine (MacOS) created successfully.

Proxmox: 7.3-3
MacOS Ventura

Reagrds,
Patrick

**Comment by Tamperold** [comment]
I have the same problem. The setup does not work because the conf file does not exist. Shouldn't it be created with the script? Unfortunately, the whole thing is therefore absolutely unusable.

**Comment by tristan-k** [comment]
> I have the same problem. The setup does not work because the conf file does not exist. Shouldn't it be created with the script? Unfortunately, the whole thing is therefore absolutely unusable.

Same here. In it's current state the script is broken if the user sets a custom VM ID. There also several other hardcoded paths (like `ISODIR=/var/lib/vz/template/iso/`) which should be defined by user interaction.

**Comment by levi2m** [comment]
that is weird, i have being using this script for a while now and never encountered this issue

and i always setup everything different from the  suggested defaults

even the allocation from the isos are on a different storage then the actual storage for the vm

**Comment by i-oliva** [comment]
I have the same problem

**Pull request merged**
