### PR TITLE
Adding some customization to the VM Setup

### PR DESCRIPTION
**Pull request by dlerps**
Allows for extra options during the setup:

- Core Count
- VM Id
- VM Name
- RAM
- Storage for Iso

### CODE REVIEW

**Review by luchina-gabriel — CHANGES_REQUESTED** [review]
Hi Daniel, how are you?

First, thanks for the PR and your contribute.

I have evaluated the changes and have some observations:

- Core Count: For macOS, amount of CPU cores needs to be power of 2, so leaving the configuration open, errors may arise for the end user.

- VM Id: It's OK

- VM Name: It's OK. It would be nice to make the other parameters the same, a default value if the user does not enter a name.

- RAM: It's OK. Leaving the default value for 4096 as opposed to 4000 would be more interesting to leave the exact value of 4Gb.

- Storage for ISO: The osx-proxmox script copies the recovery and Opencore ISOs to local storage, as it will always exist. If this adjustment exists, it may fail because new storage does not always have an ISO repository. In the ISO storage settings, there were also some differences in the name of the recovery image versus the macOS that will be installed (for all versions, the Monterey image is fixed).

Best Regards,
Gabriel Luchina

**Comment by dlerps** [comment]
Hi Gabriel. I'm fine thanks... how are you?

As for your comments:

- How about validating the core count against the limitation and adding it to the input request message?
- The storage changes I would revert for now
- I will add the default values for RAM & VM Name

**Comment by luchina-gabriel** [comment]
Hi Daniel! ;)

Core count needs to be power of 2 for Intel, and AMD are manually patch via EFI.

I have a video explaining how to get around this power of 2 when setting up INTEL.
https://youtu.be/9XaUeZRizts?list=PLf_ZhL_Y4glPSp0cw9crZlAZcFzWkw-RQ

In resume, args additional:
01, NATIVE
02, NATIVE
03, -smp 3,cores=1,sockets=3,threads=1,maxcpus=3
04, NATIVE
05, -smp 5,cores=1,sockets=5,threads=1,maxcpus=5
06, -smp 6,cores=2,sockets=3,threads=1,maxcpus=6
07, -smp 7,cores=1,sockets=7,threads=1,maxcpus=7
08, NATIVE
09, -smp 9,cores=1,sockets=9,threads=1,maxcpus=9
10, -smp 10,cores=2,sockets=5,threads=1,maxcpus=10
11, -smp 11,cores=1,sockets=11,threads=1,maxcpus=11
12, -smp 12,cores=2,sockets=3,threads=2,maxcpus=12
13, -smp 13,cores=1,sockets=13,threads=1,maxcpus=13
14, -smp 14,cores=2,sockets=7,threads=1,maxcpus=14
15, -smp 15,cores=1,sockets=15,threads=1,maxcpus=15
16, NATIVE
17, -smp 17,cores=1,sockets=17,threads=1,maxcpus=17
18, -smp 18,cores=2,sockets=9,threads=1,maxcpus=18
19, -smp 19,cores=1,sockets=19,threads=1,maxcpus=19
20, -smp 20,cores=2,sockets=5,threads=2,maxcpus=20
21, -smp 21,cores=1,sockets=21,threads=1,maxcpus=21
22, -smp 22,cores=2,sockets=11,threads=1,maxcpus=22
23, -smp 23,cores=1,sockets=23,threads=1,maxcpus=23
24, -smp 24,cores=2,sockets=6,threads=2,maxcpus=24
25, -smp 25,cores=1,sockets=25,threads=1,maxcpus=25
26, -smp 26,cores=2,sockets=13,threads=1,maxcpus=26
27, -smp 27,cores=1,sockets=27,threads=1,maxcpus=27
28, -smp 28,cores=2,sockets=7,threads=2,maxcpus=28
29, -smp 29,cores=1,sockets=29,threads=1,maxcpus=29
30, -smp 30,cores=2,sockets=15,threads=1,maxcpus=30
31, -smp 31,cores=1,sockets=31,threads=1,maxcpus=31
32, NATIVE
...
48, -smp 48,cores=2,sockets=24,threads=1,maxcpus=48
48, -smp 48,cores=2,sockets=12,threads=2,maxcpus=48

Maybe the core count adjustment is nice to keep as it is, because the fine adjustment can be done later...

Regards, 
Gabriel ;)

**Comment by dlerps** [comment]
Alright. So if I get you correctly it would be fine to leave the core allocation promt as it is implemented right now? Or did I misunderstand you there?

The other changes I just pushed as requested.

**Comment by luchina-gabriel** [comment]
Hi Daniel,

Core count can leave the original way for now, keeping the static value of 4 cores.

Maybe, create something to allow setting only power of 2 values, and in case of informing a different value, round to the smallest compatible value (power of 2). I say round down, because depending on the CPU, if you round up to the next (higher) value, there may be more cores than there are and with this, create a problem when creating the VM.

What do you think?

Gabriel

**Pull request merged**
